export const JOB_PRIORITIES = {
  CRITICAL: 1,
  HIGH: 5,
  NORMAL: 10,
  LOW: 20,
} as const;

export const DEFAULT_LEASE_DURATION_MS = 60_000;
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 5_000;
export const DEFAULT_WORKER_UNHEALTHY_THRESHOLD_MS = 30_000;
export const DEFAULT_MAX_ATTEMPTS = 3;
export const DEFAULT_INITIAL_DELAY_MS = 5_000;
export const DEFAULT_MAX_DELAY_MS = 300_000;

export const WS_EVENTS = {
  JOB_CREATED: 'JOB_CREATED',
  JOB_CLAIMED: 'JOB_CLAIMED',
  JOB_STARTED: 'JOB_STARTED',
  JOB_COMPLETED: 'JOB_COMPLETED',
  JOB_FAILED: 'JOB_FAILED',
  JOB_RETRYING: 'JOB_RETRYING',
  WORKER_ONLINE: 'WORKER_ONLINE',
  WORKER_OFFLINE: 'WORKER_OFFLINE',
  QUEUE_PAUSED: 'QUEUE_PAUSED',
  QUEUE_RESUMED: 'QUEUE_RESUMED',
  SYSTEM_EVENT: 'SYSTEM_EVENT',
} as const;
